live_config_reload = true

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#000000'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'
[font]
size = 18
# ligatures = true

[font.bold]
family = "Hasklug Nerd Font"
style = "Bold"

[font.italic]
family = "Hasklug Nerd Font"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.6
blur = true
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 2
y = 2

[scrolling]
history = 10000
multiplier = 3


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[mouse]
hide_when_typing = false

[cursor]
style = "Block"
unfocused_hollow = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
